### ISSUE TITLE
What exactly is the difference between implementing single- and multi-transaction tests?

### ISSUE THREAD

**Issue by hmijail** [ConsenSys/evm-dafny#487]
(A2 in roadmap)

BlockchainTests are run by `retesteth` + `evm t8n`. 
`evm t8n` can in appearance be implemented easily in terms of `evm statetest`, which we already mostly have. But who is actually keeping the world/blockchain state between transactions and blocks? Do we need to implement that, or does retesteth do it?

- [x] Dump input and output from t8n, as driven by retesteth
- [x] Relate those to filled and filler BlockchainTest JSON files
- [x] Decide who does what, and what we need to implement

**Comment by DavePearce** [comment]
I think the main difference between the tests is: 

1. **State Tests**.  These only ever execute a single transaction.
2. **Block Chain Tests**.  These can execute more multiple blocks, each of which can contain multiple transactions.

The information contained in the block chain tests is also presented in a different style.  The block information is encoded fully in the RLP format, and includes various other details.  So, we have to unpack all of that and decide which bits of it we want to check.

**Comment by DavePearce** [comment]
> But who is actually keeping the world/blockchain state between transactions and blocks?  Do we need to implement that, or does retesteth do it?

We currently have no internal notion of a block.  So, to run the tests fully ourselves (i.e. without retesteth) this is something we would need to add.  At the moment, retesteth is not part of our testing pipeline.  However, I think (maybe?) retesteth would do this for us if we implemented either the `t8n` or `t9n` interface (I'm not sure which is better?).  

So, I'd suggest two ways forward (in no particular order):

1. Improve `evm statetest` to the point where we can plug it into retesteth.
2. Add command-line options for `evm t8n` and/or `evm t9n`.  In principle, I feel like that should be straightforward, but I'm sure there will be some details.

I don't know which of these is better to focus on first?  Also, I don't actually know how you would execute one of the `BlockChainTests` using Geth's `evm` tool either.  So if anyone knows anything about that I'd be happy to hear more!

**Comment by DavePearce** [comment]
> But who is actually keeping the world/blockchain state between transactions and blocks?

Sorry, just thinking about this.  When using `evm t8n` this information is serialised into `alloc.json`.  By default, I think that file is updated when you run `evm t8n` (could be wrong about that).  You can also specify a different location to place the updated file using `--output.alloc`.

Is that sort of helping ?

**Comment by hmijail** [comment]
While looking into this I noticed that the Berlin fork contains about 13K tests, London about 20K, and Paris/Merge about 21K.
So moving to a more current fork would give us over 30% more tests.

Moving to London would mean adding the BASEFEE opcode.
Moving to Paris/Merge would mean changing the DIFFICULTY opcode to PREVRANDAO.

**Comment by hmijail** [comment]
Retesteth might be on the way to getting deprecated. For now [the alternative seems barely started](https://github.com/ethereum/execution-spec-tests), but in any case `evm t8n` will remain as the geth interface for testing at the EVM level.

T8n doesn't read test files directly. Instead it needs a driver that will feed it parameters from the test files. Retesteth is the perfect driver when implementation is finished and we only need to check that end results are as expected.

However, when needing traces for debugging, t8n generates those traces with little flexibility and retesteth doesn't help. This is still OK for small traces, but blocks us from improving the workflow for long running tests / big traces. I asked long ago for small improvements in both t8n and retesteth so that we would be able to use unix pipes (https://github.com/ethereum/retesteth/issues/179). If those don't get implemented, then the easiest solution will be to do our own parser/driver instead of using retesteth.

Red herrings / pitfalls:
* t8n for multi-transaction test: less than 20 tests are actually multi-transaction in a single block. Supporting these requires RLP decoding and implementing their own flow. Only worth it if very easy to implement once we have single-transaction.
* evm statetest: more common interface than t8n. Problems: for input, it just packs together all the inputs - but requires dealing with parameter ranges. For output, it only reports world state hashes, so it requires implementing storage tries. Could be useful to support for fuzzing, and that only requires non-ranged-inputs and ignoring outputs; should be easy to implement on top of t8n.

**Comment by DavePearce** [comment]
> If those don't get implemented, then the easiest solution will be to do our own parser/driver instead of using retesteth.

For reference, this is what the EvmTools library does for us (for the state tests).  It parses the state test files, and feeds the individual test instances they contain into Geth's `evm` tool.  It then parses the trace output and packages all of the information into a single `json` file which is then stored in the `evm-dafny` repository.

**Comment by hmijail** [comment]
> EvmTools library 

Yes, I looked into that already. Problems:
* It works from GeneralStateTest files, which as mentioned in the red herrings/pitfalls for `evm statetest`, only provide a goal worldstate hash. In contrast, BlockchainTest files give a post-state that is immediately useful, plus are simpler to parse, since they don't require to deal with ranges of values and mapping them to results.

* It stores traces, which is a source of logistic problems I'm trying to avoid. Of note, the maintainers of the Common tests considered and rejected storing traces in the past. That's why I'm pushing to use pipes.

**Comment by DavePearce** [comment]
> It stores traces, which is a source of logistic problems I'm trying to avoid

Well, its not a problem we are experiencing at this time.  Perhaps, at some point, it could be an issue.  But, I wouldn't personally design a solution based around a problem we don't yet have.  

But, ok, let's think the design of this through a little bit.  If I understand correctly, we'd need to run Geth's `evm` tool in (roughly speaking) lock step with the DafnyEvm.  Basically, read a bunch of lines from `evm` and then a bunch of lines from `DafnyEvm`, then compare and repeat.  If a difference is found then it can print out the diff.  For debugging we can add a mode which keeps the entire history for a given test so it can be printed out at the point of difference.

I think it could work (but wouldn't be 100% sure unless I actually tried to build it).  I'd guess it pushes up memory requirements for the machine running the tests (i.e. our developer's machines).  That's probably something we can manage with care (e.g. using abbreviated hex strings as I did before, or maybe just compressing chunks immediately and comparing compressed blobs and unpacking when there's a difference).  It will also increase the build time since we're basically doing everything twice in real time (it currently takes my system `16m` to push Geth through all the tests with tracing enabled versus `2m35` for a full build + all testing of the Dafny EVM).  We'd need a system to coordinate and run tests from the statetest JSON files.  You could try to use retesteth for this by using a wrapper around `evm statetest` which actually runs both tools.

Anyway, to do all this and make it work is a big project in itself.  I feel like taking this on _and_ working on migrating to Go ... is a tough challenge!

**Comment by DavePearce** [comment]
Hmmmm, perhaps I am overthinking the design here a little.  No surprises there.  A simpler approach is to run Geth's `evm` tool using a specialised wrapper, and then send the output to a temporary file.  Then, that file is read by the testing framework for the DafnyEVM.  In fact, we actually could already do that now!!  If you run this:

```
gradle testgen
```
Then it regenerates all of the json trace test files using Geth.  Then you can run `gradle test` to run the Dafny EVM on them.  At the moment the JSON files are stored in the repository, but you could regenerate them on every build.  With caching enabled, that could made to work in some kind of reasonable timeframe.  Even on the CI pipeline you can cache certain artifacts.

Is that the kind of solution you are looking for?

**Comment by DavePearce** [comment]
So, some back of the envelope testing (since I didn't do this before and its interesting).  He's my test script:

```bash
#/bin/bash

echo "Running and compressing $1..."
time `evm --json --nomemory=false statetest $1 2>&1 | bzip2 --stdout > output.bz2`
```

Here's an example:

```
./run.sh fixtures/GeneralStateTests/stMemoryTest/stackLimitPush31_1023.json
Running and compressing fixtures/GeneralStateTests/stMemoryTest/stackLimitPush31_1023.json...

real    3m26.413s
user    3m37.324s
sys     0m1.111s
```

The compressed file `output.bz2` is around `800K`, and uncompressed is just over `1G`.  That contrasts with our (uncompressed) JSON file which is around `8M`.

**Comment by hmijail** [comment]
> Well, its not a problem we are experiencing at this time. Perhaps, at some point, it could be an issue. But, I wouldn't personally design a solution based around a problem we don't yet have.

Actually in the very first small batch of test traces that I prepared, back in August, some of them were already over 4 GB (and I'd swear there was one over 17GB). 

> But, ok, let's think the design of this through a little bit. If I understand correctly, we'd need to run Geth's evm tool in (roughly speaking) lock step with the DafnyEvm. Basically, read a bunch of lines from evm and then a bunch of lines from DafnyEvm, then compare and repeat. If a difference is found then it can print out the diff. 

Yes, that's what pipes do for us.
```
mkfifo pipe1
evm t8n testfile --trace > pipe1
mkfifo pipe2
dafny-evm t8n testfile --trace > pipe2
diff pipe1 pipe2
```
Done.

(Instead of diff we would have our own program which keeps a copy of the stream, jumps into debugging of dafny-evm at the point of failure, or whatever else we want. But the idea is the same.)


> For debugging we can add a mode which keeps the entire history for a given test so it can be printed out at the point of difference.
>
> I think it could work (but wouldn't be 100% sure unless I actually tried to build it). I'd guess it pushes up memory requirements for the machine running the tests (i.e. our developer's machines). That's probably something we can manage with care (e.g. using abbreviated hex strings as I did before, or maybe just compressing chunks immediately and comparing compressed blobs and unpacking when there's a difference). It will also increase the build time since we're basically doing everything twice in real time (it currently takes my system 16m to push Geth through all the tests with tracing enabled versus 2m35 for a full build + all testing of the Dafny EVM). We'd need a system to coordinate and run tests from the statetest JSON files. You could try to use retesteth for this by using a wrapper around evm statetest which actually runs both tools.

I'd wait until we find a problem, see what exactly is the problem, and how exactly we solve it. 
But the easy answer is: 
1. run the test in normal mode, check result vs test's declared end state. Just what retesteth does in a normal test run.
2. If incorrect result, re-run in differential mode, which necessarily has to be slow - but with pipes at least we avoid the logistics of huge files.

> So, some back of the envelope testing (since I didn't do this before and its interesting).

Generating a compressed trace for one test is easy, and you might remember I proposed that months ago instead of creating our own incompatible formats and infrastructure.

But doing that for thousands of tests turns into a logistics problem (creation, storage, moving around, updating), which is what I want to avoid.

**Comment by hmijail** [comment]
Closing this issue because its goal is finished.

**Comment by DavePearce** [comment]
```
Actually in the very first small batch of test traces that I prepared, back in August, some of them were already over 4 GB (and I'd swear there was one over 17GB).
```

Right, but the largest JSON file we have in the repository is `19m` at the moment --- so it really is not a problem.

```
mkfifo pipe1
evm t8n testfile --trace > pipe1
mkfifo pipe2
dafny-evm t8n testfile --trace > pipe2
diff pipe1 pipe2
```

That's not a solution.  Its not a replacement for what we have.  How do I run this over all the tests whist ignoring those currently unsupported?  How do I run it in the IDE?  How do I run this in the CI pipeline?  How do I get useful debug output? (hint: `diff` won't give you that)  To turn this into a replacement for what we have, a system needs to be written which controls it and manages the output.  You can do that in `bash`, `go`, `java`, `python` or whatever language suits.  

```
Generating a compressed trace for one test is easy, and you might remember I proposed that months ago instead of creating our own incompatible formats and infrastructure.
```

It can generate compressed outputs actually.  But, after researching `git` a bit, it seems its not worth compressing as git already compresses for us in the repository.  

```
instead of creating our own incompatible formats and infrastructure.
```

So ... you are just going to create your own incompatible infrastructure instead?  That's how it seems to me.  That's why I am confused about all of this.

**Comment by hmijail** [comment]
> 
> Actually in the very first small batch of test traces that I prepared, back in August, some of them were already over 4 GB (and I'd swear there was one over 17GB).
> Right, but the largest JSON file we have in the repository is 19m at the moment --- so it really is not a problem.
> 

But the goal is to move past what we have at the moment, IIUC?

> mkfifo pipe1
> evm t8n testfile --trace > pipe1
> mkfifo pipe2
> dafny-evm t8n testfile --trace > pipe2
> diff pipe1 pipe2
> That's not a solution. Its not a replacement for what we have. How do I run this over all the tests whist ignoring those currently unsupported? How do I run it in the IDE? How do I run this in the CI pipeline? How do I get useful debug output? (hint: diff won't give you that) To turn this into a replacement for what we have, a system needs to be written which controls it and manages the output. You can do that in bash, go, java, python or whatever language suits.
> 
Yes, those 5 lines are the skeleton of the idea, not the finished solution, of course. And that's why I said "Instead of diff...", etc. That's why I am still working on it I guess?

Re: IDE and CI: what exactly is the problem?

**Comment by DavePearce** [comment]
> But the goal is to move past what we have at the moment, IIUC?

Well, I'm not sure what the goal is here.  I don't actually see a reason to move past what we have.  Its working and doing a reasonable job.  There are some problems I know of though, and when you get `evm statetest` for the Dafny EVM working ... I think you find them quickly putting it through retesteth.  But they are all fixable.

> Yes, those 5 lines are the skeleton of the idea, not the finished solution, of course. And that's why I said "Instead of diff...", etc. That's why I am still working on it I guess?

Yeah, and fair enough --- I get that (actually I think `fifo` pipes is a neat idea).  But, you're replacing one piece of (testing) infrastructure with another piece of infrastructure.  But, I'm not seeing any actual gain for us?  I appreciate you don't like the existing infrastructure, but I'm not sure what you don't like about it?  Its about as simple as it gets, and just wraps the statetest file and JSON trace output into a single JSON file.  You could keep them separate ... but I don't see a huge advantage.

> Re: IDE and CI: what exactly is the problem?

Well, realistically, CI shouldn't be a problem other than the how long it might take or how much RAM it uses.  Already waiting for PR to get the green light ... takes what seems like forever.

For the IDE, this is just about the debugging process.  Currently, DafnyEVM developers can run the tests in VSCode (or Eclipse), get the diff output, select which tests to run, etc.  In short, they get all the benefits of an existing and widely used testing framework (JUnit).

**Comment by DavePearce** [comment]
> But the goal is to move past what we have at the moment, IIUC?

Hmmm, just thinking in the context of this issue.  Certainly, one possible thing is to extend further to support block tests as well as state tests.  Is that what you meant?

**Comment by hmijail** [comment]
> 
> But the goal is to move past what we have at the moment, IIUC?
> 
> Well, I'm not sure what the goal is here. I don't actually see a reason to move past what we have.
> 
I thought that was discussed already. Motivations to move to t8n vs statetest, etc. To rediscuss please go to that "proposed roadmap" I posted a couple of weeks ago, or in the channel?

> But, you're replacing one piece of (testing) infrastructure with another piece of infrastructure.
> 

No, I'm trying to reuse and be compatible with existing infrastructure as much as possible. That's why I keep referring to retesteth and t8n. Compatibility with the ecosystem (while dogfooding/improving it), integration with a client, etc. Again, I thought this was discussed already?

> Well, realistically, CI shouldn't be a problem other than the how long it might take or how much RAM it uses. Already waiting for PR to get the green light ... takes what seems like forever.
> 
So take the numbers and let's see what makes sense later. "Seems like forever" is not very actionable.

> For the IDE, this is just about the debugging process. Currently, DafnyEVM developers can run the tests in VSCode (or Eclipse), get the diff output, select which tests to run, etc. In short, they get all the benefits of an existing and widely used testing framework (JUnit).
> 
But, following your own prompt, we decided we are moving away from Java and towards Go, right? So at the very least JUnit would also go, with Gradle, etc?

Anyway, I haven't seen that workflow so I just don't know. But I assume that we'll want to run ALL tests (or a single one) and stop and debug in the one that fails. What other use case is there?

**Comment by DavePearce** [comment]
> I thought that was discussed already. Motivations to move to t8n vs statetest, etc. To rediscuss please go to that "proposed roadmap" I posted a couple of weeks ago, or in the channel?

I would say we agreed to add support for these interfaces, not to replace the entire testing infrastructure.  Eventually, we might choose to do that.  But one step at a time.  Using the interfaces to run the DafnyEVM through retesteth, to support fuzzing, etc --- that all makes sense.

Its this line which has confused me:

> It stores traces, which is a source of logistic problems I'm trying to avoid

I'm not seeing any issues with storing the traces.  I also don't see it as being in compatible with existing infrastructure.  Its seem like an unrelated issue ?

> So take the numbers and let's see what makes sense later. "Seems like forever" is not very actionable.

I definitely agree.  But I am trying to signal that these are primary concerns here.

> But, following your own prompt, we decided we are moving away from Java and towards Go, right? So at the very least JUnit would also go, with Gradle, etc?

I would suggest that we have decided to investigate moving away from Java to Go.  But, we can't make a strong decision on whether to abandon Java until we have all the information.  Specifically, when we have the Java and Go systems running side-by-side.  At that point, we can the decision to deprecate.  Until then, we cannot make the decision.  Its quite a long road to get to that point.  But, regardless of whether we choose to eventually deprecate Java, there are benefits:

- Moving existing Java code => Dafny (where it makes sense to do it) is a clear win.

- Supporting additional backends seems at least useful, and potentially important (e.g. if running in go allows things we cannot do in Java).  That is one of the items in our list of projects we made, so it makes sense.

But there is a long road to go down to get this all working.  There are quite a few steps, and any one of them could throw up serious issues.

> Anyway, I haven't seen that workflow so I just don't know. But I assume that we'll want to run ALL tests (or a single one) and stop and debug in the one that fails. What other use case is there?

Well, personally, I think it would be a good idea to try and use it.  That way, you'll get some understanding of what is good (or bad) about it.  Its a challenge because I don't know if there are any easy issues left to close which require debugging some problem (and hence getting experience with the process).  But we can have a look for some.  Or, you could  migrate some small component from Java to Dafny (e.g. I'd suggest blake2b as a self contained and relatively straightforward migration task).
