### ISSUE TITLE
Dafny tests: verification vs runtime

### ISSUE THREAD

**Issue by hmijail** [ConsenSys/evm-dafny#501]
Most files in /src/test/dafny aren't runtime tests and instead only exercise the verifier. It would be good to clarify what each does.

The ones that are runtime tests need their own build stage.
The ones that aren't, probably don't and slow the build. Even, are they redundant?

**Comment by DavePearce** [comment]
Yeah, so there is definitely a discrepancy here.  Let's take two examples:

From `ByteTests.dfy`:

```Dafny
 method {:test} ReadTests() {
        // U8
        Assert(() => ReadUint8([],0) == 0);
        Assert(() => ReadUint8([0],0) == 0);
        ...
 }
```

Versus this from `Test10`:

```Dafny
method {:test} main1() {
        var vm := EvmBerlin.InitEmpty(0);
        var a: u8 := 0x01;
        var b: u8 := 0x02;
        ghost var st := vm.GetStack();
        vm := Push1(vm, a);
        vm := Push1(vm, b);
        vm := Add(vm);
        assert vm.Peek(0) as nat == (a + b) as nat;
        vm := Pop(vm);
        assert vm.GetStack() == st;
    }
```

For the record, the key difference here is the use of `Assert()` in the first but only `assert` in the latter.  This means that the latter assertion is **not** being tested at runtime.  The reason for both verifying _and_ executing these tests may seem odd as, if the test is verified as correct, then it should execute correctly (right?).  Well, the point is capture mis-compilations by the supported Dafny backends (of which we have found a few issues already).

In the above case, we can replace the `assert` as follows:

```
     ...
     Assert(() => vm.Peek(0) as nat == (a + b) as nat);
     ...
```

That is fine.  For the second `assert` we get this:

```
    ...
    Assert(() => vm.GetStack() == st);
    ...
```

This fails because `st` is marked as `ghost`.  If we remove that modifier, then it works.

**Comment by DavePearce** [comment]
The above illustrates a situation where we can convert a test from using `assert` to using `Assert()`.  Points to note:

- (**Do**) Wherever we can convert `assert` to `Assert()`, _we should do so_.

- (**Maybe**) In some cases, the conversion doesn't make sense (e.g. `inc_proof()` in `FM-paper.dfy`).  Note, however, we may still be able to do the conversion --- it just won't add anything new.

**Comment by DavePearce** [comment]
So, for that particular example I made it work with these changes:

```Dafny
include "../../dafny/evms/berlin.dfy"
include "utils.dfy"

/** Provide some tests to check some qualitative properties of bytecode.
 *
 *  We use an EVM with no gas as the bytecode high-level instructions
 *  like `Push1` do not consume gas.
 */
module Test10 {
    ...
    import Stack
    import opened Utils

    /**
     *   A very simple linear program manipulating the stack.
     *
     */
    method {:test} main1()
    {
        ...
        Assert(() => vm.Peek(0) as nat == (a + b) as nat);
```

**Comment by DavePearce** [comment]
Well, the point of calling it `Assert` is exactly to make clear the close connection with `assert`!  Another name is possible if we can find a good one.  Random thoughts: `RuntimeAssert()`, `ExecutableAssert()`, `RunnableAssert()` ... dunno.

**Comment by hmijail** [comment]
I'd vote AssertAndExpect 😇

**Comment by DavePearce** [comment]
Well, it's long.  But, it does what it says on the tin.  The other ones I thought of were `DoubleAssert`, `DualAssert`, etc.

**Comment by DavePearce** [comment]
To clarify, I am happy with `AssertAndExpect`.  If you want to make that change, then raise a separate issue for it.  I would then have a second issue which is to convert all existing tests to use `AssertAndExpect`, and to add modules as necessary.

**Comment by hmijail** [comment]
> (adding modules as necessary for this to work)

I think the main place that was needed was in the utils.dfy file itself which I already did... but didn't look deeper.
